version: "3"

services:
    dbdesigner:
        build: .
        depends_on: 
            - proxy
        restart: always
        volumes:
            - ./docs:/usr/app/docs
            - ./public:/usr/app/public
            - ./src:/usr/app/src
        networks:
            - no-internet
        ports:
            - 8080

    proxy:
        image: nginx:1.17.6-alpine
        restart: always
        networks:
            - internet
            - no-internet
        volumes:
            - ./docker.nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8082:80"

# Disabling internet access guarantees your confidentiality
networks:
    no-internet:
        driver: bridge
        internal: true
    internet:
        driver: bridge
